# Generated by Django 2.1 on 2018-08-04 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0002_auto_20180804_2226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reading',
            name='lesson',
        ),
        migrations.AddField(
            model_name='reading',
            name='lessons',
            field=models.ManyToManyField(to='curriculum.Lesson'),
        ),
    ]
