# Generated by Django 2.1 on 2018-08-12 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0006_auto_20180812_0211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='day',
        ),
        migrations.AddField(
            model_name='day',
            name='lessons',
            field=models.ManyToManyField(to='curriculum.Lesson'),
        ),
    ]
